<?php
/**
 * admin模块所有控制器的基类
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/24
 * Time: 14:53
 */
namespace app\admin\controller;

use think\Controller;
use think\Request;
use think\Hook;
class AdminBase extends Controller
{
    protected $Rinstance;

    /**
     * 初始化方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Rinstance = Request::instance();
        $action = "check_auth";
        Hook::listen('checkauth', $action);
    }

}