<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/23
 * Time: 16:13
 */
namespace app\admin\controller;

use think\Controller;
use app\common\model\CheckLogin;
use think\Hook;
use think\Request;
use think\Session;
use think\Url;
class Login extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $action="check_auth";
//        Hook::listen('checkauth',$action);
    }

    /**
     * 登陆展示页面
     * @return mixed
     */
    public function login()
    {
        return $this->fetch("login");
    }

    public function index()
    {

        return (new CheckLogin)->checklogin();
//       $request=Request::instance()->post();
//        if(!captcha_check($request['captcha'])){
//            //验证失败
//            return ["msg"=>"验证码错误","status"=>"error"];
//        };
    }

    /**
     * 退出登陆
     */
    public function loginout()
    {
        Session::clear();
        return ["url"=>Url::build("admin/login/login")];
    }
}






