<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/23
 * Time: 16:13
 */
namespace app\admin\controller;

use think\Controller;
use app\common\model\CheckLogin;
use think\Crypt\driver\Crypt;
use think\Hook;
use think\Request;
class Login extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $action="checkCookie";
        Hook::listen('checkauth',$action);
    }

    /**
     * 登陆展示页面
     * @return mixed
     */
    public function login()
    {
        return $this->fetch("login");
    }

    /**
     * 登陆首页
     * @return array|bool
     */
    public function index()
    {
        return (new CheckLogin)->checklogin();
    }

}






