<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/24
 * Time: 14:53
 */
namespace app\index\controller;

use think\Controller;
use think\Request;

class IndexBase extends Controller
{
    protected $Rinstance;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Rinstance = Request::instance();
    }

    /**
     * 接收并assign到页面flag
     */
    public function assignFlag()
    {
        $this->assign([
            "flag" => $this->Rinstance->param('flag')
        ]);
    }
}